package de.ltt.server.reflaction;

public enum Rights {
	MAIN_DAUERVERTRAG(6), 	//  späda
	MAIN_INVITE(6),			// 
	MAIN_UNINVITE(6),
	MAIN_BUYFIRMHOUSE(6),
	MAIN_SELLFIRMHOUSE(6),
	MAIN_SELLFIRM(6),
	MAIN_SETPAY(6),
	MAIN_SETRIGHTS(6),
	MAIN_CHANGENAME(6),
	MAIN_FIRMINFO(6),
	MAIN_FIRMINFORIGHTS(6),
	MAIN_CONTROLLMACHINES(6),
	MAIN_BUYEXTERNPRODUCTS(6),
	MAIN_RANKUP(6),
	MAIN_RANKDOWN(6),
	MAIN_CHARGEMONEY(6),
	SELL_CHANGEPRICE(6),
	SELL_SETPRODUCTS(6),
	SELL_SELLPROTUCTS(6),
	PROC_SELLPRODUCTS(6),
	PROC_CHANGEPRICE(6),
	PROC_SETPRODUCTS(6),
	MINE_BUYBUILDPLACE(6),
	MINE_SETPRODUCTS(6),
	MINE_SELLPRODUCTS(6),
	MINE_CHANGEPRICE(6),
	IMMO_BUYPHOUSE(6),
	IMMO_SELLPHOUSE(6),
	IMMO_SETPRICE(6),
	LAWS_BUYBUILDPLACE(6),
	LAWS_SETPRODUCTS(6),
	LAWS_SELLPRODUCTS(6),
	LAWS_CHANGEPRICE(6),
	WATE_SETTARIFS(6),
	WATE_SELLTARIF(6),
	WATE_SETWATERPRICE(6),
	WATE_SELLWATER(6),
	ENER_SETTARIF(6),
	ENER_SELLTARIF(6),
	ENER_BUYBURNMATERIAL(6),
	ENER_SETBURNMATERIAL(6),
	GARB_GETWASTE(6),
	GARB_SETPRODUCTS(6),
	GARB_SELLPRODUCTS(6),
	GARB_SETATOMICWASTEPLACE(6);
	
	
	
	private int translation;
	
	private Rights(int translation) {
		this.translation = translation;
	}
	
	public int getTranslation() {
		return translation;
	}
	
	public void setTranslation(int translation) {
		this.translation = translation;
	}
}
